export class ScriptDb {
    public static index = [
        {
            "id": 634,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "123",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125777119",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 633,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125773621",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 632,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125769385",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 631,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125763104",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 630,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125757398",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 629,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125752634",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 628,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125749520",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 627,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515125566400",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 626,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124412467",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 625,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124408493",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 624,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124405062",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 623,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124401299",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 622,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124398553",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 621,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124389908",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 620,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/dashboard",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/dashboard",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/dashboard",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124382699",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 619,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124373855",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 618,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124369824",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 617,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124320720",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 616,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124305737",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        },
        {
            "id": 615,
            "projectRoot": "http://127.0.0.1:4200",
            "context": "/script",
            "metaData[script][src]": "",
            "metaDate[script][content]": null,
            "releaseStage": "production",
            "url": "http://127.0.0.1:4200/script",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
            "language": "zh-CN",
            "sevrity": null,
            "name": "SyntaxError",
            "message": "Uncaught SyntaxError: Unexpected token )",
            "stacktrace": "SyntaxError: Unexpected token )",
            "file": "http://127.0.0.1:4200/script",
            "lineNumber": 32,
            "columnNumber": 5,
            "payloadVersion": "2",
            "ct": "img",
            "cb": "1515124262536",
            "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9"
        }
    ]
    

    public static l = {
        "apiKey": "qetBqF9Ja3v2oU8BRRzoLlWaKj0cFiN9",
        "notifier": {
            "name": "Bugsnag JavaScript",
            "version": "4.1.1",
            "url": "https://github.com/bugsnag/bugsnag-js"
        },
        "events": [{
            "payloadVersion": "4",
            "exceptions": [{
                "errorClass": "SyntaxError",
                "message": "Unexpected token )",
                "stacktrace": [{
                    "file": "SyntaxError: Unexpected token ",
                    "lineNumber": 33,
                    "columnNumber": 5
                }],
                "type": "browserjs"
            }],
            "severity": "error",
            "unhandled": true,
            "severityReason": { "type": "unhandledException" },
            "app": { "releaseStage": "production" },
            "device": {
                "time": "2018-01-06T16:40:52.896Z",
                "locale": "zh-CN",
                "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML,like Gecko) Chrome/63.0.3239.84 Safari/537.36"
            },
            "breadcrumbs": [{
                "type": "navigation",
                "name": "Bugsnag loaded",
                "timestamp": "2018-01-06T16:40:52.891Z",
                "metaData": {}
            }],
            "context": "/script",
            "user": {},
            "metaData": {},
            "request": { "url": "http://127.0.0.1:4200/script" }
        }]
    }
}