export default {
    activities: [
        {
            index: 0,
            serverSessionId: '5dda91504aea244982de72d1',
            time: -1,
            timestamp: 1574605136262,
            type: 'dom_snapshot',
            data: {
                docType: '<!DOCTYPE html>',
                left: 0,
                origin: 'http://127.0.0.1:8081/test.html',
                pageUrl: 'http://127.0.0.1:8081/test.html',
                referrer: null,
                screenWidth: 1623,
                top: 0,
                visibilityState: 'visible',
                snapshot: {
                    tagName: 'HTML',
                    attributes: [{ name: 'lang', value: 'en' }],
                    nodeType: 1,
                    id: 2,
                    childNodes: [
                        {
                            tagName: 'HEAD',
                            nodeType: 1,
                            id: 5,
                            childNodes: [
                                { textContent: '\n    ', nodeType: 3, id: 20 },
                                {
                                    tagName: 'META',
                                    attributes: [{ name: 'charset', value: 'UTF-8' }],
                                    nodeType: 1,
                                    id: 27,
                                },
                                { textContent: '\n    ', nodeType: 3, id: 35 },
                                {
                                    tagName: 'META',
                                    attributes: [
                                        { name: 'name', value: 'viewport' },
                                        { name: 'content', value: 'width=device-width, initial-scale=1.0' },
                                    ],
                                    nodeType: 1,
                                    id: 44,
                                },
                                { textContent: '\n    ', nodeType: 3, id: 54 },
                                {
                                    tagName: 'META',
                                    attributes: [
                                        { name: 'http-equiv', value: 'X-UA-Compatible' },
                                        { name: 'content', value: 'ie=edge' },
                                    ],
                                    nodeType: 1,
                                    id: 65,
                                },
                                { textContent: '\n    ', nodeType: 3, id: 77 },
                                {
                                    tagName: 'TITLE',
                                    nodeType: 1,
                                    id: 90,
                                    childNodes: [{ textContent: 'apm demo', nodeType: 3, id: 324 }],
                                },
                                { textContent: '\n\n    ', nodeType: 3, id: 104 },
                                {
                                    tagName: 'SCRIPT',
                                    attributes: [{ name: 'async', value: '' }, { name: 'src', value: 'apm.js' }],
                                    nodeType: 1,
                                    id: 119,
                                },
                                {
                                    tagName: 'SCRIPT',
                                    attributes: [{ name: 'type', value: 'text/javascript' }],
                                    nodeType: 1,
                                    id: 135,
                                    childNodes: [
                                        {
                                            textContent:
                                                '\n        ! function (a, b) {\n            var c = window;\n            c.SessionStack = a, c[a] = c[a] || function () {\n                c[a].q = c[a].q || [], c[a].q.push(arguments)\n            }, c[a].t = b;\n            var d = document.createElement("script");\n            d.async = 1, d.src = "apm.js";\n            var e = document.getElementsByTagName("script")[0];\n            e.parentNode.insertBefore(d, e);\n        }("apm", "cbf379b9df19461a949be4f54f5a4b41");\n    ',
                                            nodeType: 3,
                                            id: 350,
                                        },
                                    ],
                                },
                                { textContent: '\n', nodeType: 3, id: 152 },
                            ],
                        },
                        { textContent: '\n\n', nodeType: 3, id: 9 },
                        {
                            tagName: 'BODY',
                            nodeType: 1,
                            id: 14,
                            childNodes: [
                                { textContent: '\n    ', nodeType: 3, id: 170 },
                                { tagName: 'INPUT', attributes: [{ name: 'value', value: '' }], nodeType: 1, id: 189 },
                                { textContent: '\n    ', nodeType: 3, id: 209 },
                                {
                                    tagName: 'DIV',
                                    attributes: [{ name: 'id', value: 'app' }],
                                    nodeType: 1,
                                    id: 230,
                                    childNodes: [
                                        {
                                            tagName: 'DIV',
                                            nodeType: 1,
                                            id: 377,
                                            childNodes: [
                                                {
                                                    tagName: 'H1',
                                                    nodeType: 1,
                                                    id: 434,
                                                    childNodes: [
                                                        { textContent: 'stbui demo', nodeType: 3, id: 527 },
                                                        { textContent: '下午10:18:55', nodeType: 3, id: 560 },
                                                    ],
                                                },
                                                {
                                                    tagName: 'H1',
                                                    nodeType: 1,
                                                    id: 464,
                                                    childNodes: [
                                                        { textContent: 'number: ', nodeType: 3, id: 594 },
                                                        { textContent: '0', nodeType: 3, id: 629 },
                                                    ],
                                                },
                                                {
                                                    tagName: 'BUTTON',
                                                    attributes: [
                                                        {
                                                            name: 'style',
                                                            value:
                                                                'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                                        },
                                                    ],
                                                    nodeType: 1,
                                                    id: 495,
                                                    childNodes: [{ textContent: 'button', nodeType: 3, id: 665 }],
                                                },
                                            ],
                                        },
                                    ],
                                },
                                { textContent: '\n\n\n', nodeType: 3, id: 252 },
                                {
                                    tagName: 'SCRIPT',
                                    nodeType: 1,
                                    id: 275,
                                    childNodes: [
                                        {
                                            textContent:
                                                '!function(t){var e={};function n(o){if(e[o])return e[o].exports;var r=e[o]={i:o,l:!1,exports:{}};return t[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=t,n.c=e,n.d=function(t,e,o){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:o})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)n.d(o,r,function(e){return t[e]}.bind(null,r));return o},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=0)}([function(t,e,n){"use strict";function o(t,e){return!e||"object"!==l(e)&&"function"!=typeof e?function(t){if(void 0===t)throw new ReferenceError("this hasn\'t been initialised - super() hasn\'t been called");return t}(t):e}function r(t){return(r=Object.setPrototypeOf?Object.getPrototypeOf:function(t){return t.__proto__||Object.getPrototypeOf(t)})(t)}function i(t,e){if("function"!=typeof e&&null!==e)throw new TypeError("Super expression must either be null or a function");t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:!0,configurable:!0}}),e&&u(t,e)}function u(t,e){return(u=Object.setPrototypeOf||function(t,e){return t.__proto__=e,t})(t,e)}function c(t,e){if(t!==e)throw new TypeError("Cannot instantiate an arrow function")}function l(t){return(l="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t})(t)}function a(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}function f(t,e){for(var n=0;n<e.length;n++){var o=e[n];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(t,o.key,o)}}function s(t,e,n){return e&&f(t.prototype,e),n&&f(t,n),t}var p=function(){function t(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{};a(this,t),this.state={},this.props=e}return s(t,[{key:"setState",value:function(t){Object.assign(this.state,t),b(this)}}]),t}();function d(t,e,n){if("className"===e&&(e="class"),/on\\w+/.test(e))t[e=e.toLowerCase()]=n||"";else if("style"===e)if(n&&"string"!=typeof n){if(n&&"object"===l(n))for(var o in n)t.style[o]=n[o]}else t.style.cssText=n||"";else e in t&&(t[e]=n||""),n?t.setAttribute(e,n):t.removeAttribute(e,e)}function b(t){var e,n=t.render();t.base&&t.componentWillUpdate&&t.componentWillUpdate(),e=m(n),t.base&&(t.componentDidUpdate?t.componentDidUpdate():t.componentDidMount&&t.componentDidMount()),t.base&&t.base.parentNode&&t.base.parentNode.replaceChild(e,t.base),t.base=e}function y(t,e){return e.appendChild(m(t))}function m(t){var e=this;if(void 0!==t&&null!==t&&"boolean"!=typeof t||(t=""),"number"==typeof t&&(t=String(t)),"string"==typeof t)return document.createTextNode(t);if("function"==typeof t.tag){var n=function(t,e){var n;return t.prototype&&t.prototype.render?n=new t(e):((n=new t(e)).constructor=t,n.render=function(){return this.constructor(e)}),n}(t.tag,t.attrs);return function(t,e){t.componentWillMount?t.componentWillMount():t.componentWillReceiveProps&&t.componentWillReceiveProps(e),t.props=e,b(t)}(n,t.attrs),n.base}var o=document.createElement(t.tag);return t.attrs&&Object.keys(t.attrs).forEach(function(n){c(this,e);var r=t.attrs[n];d(o,n,r)}.bind(this)),t.children.forEach(function(t){return c(this,e),y(t,o)}.bind(this)),o}var h={createElement:function(t,e){for(var n=arguments.length,o=new Array(n>2?n-2:0),r=2;r<n;r++)o[r-2]=arguments[r];return{tag:t,attrs:e,children:o}}},v={render:function(t,e){return c(this,void 0),e.innerHTML="",y(t,e)}.bind(void 0)},g=(function(t){c(this,void 0),console.log(t)}.bind(void 0),function(t){function e(t){var n;return a(this,e),(n=o(this,r(e).call(this,t))).state={num:0},n}return i(e,p),s(e,[{key:"onClick",value:function(){this.setState({num:this.state.num+1})}},{key:"componentWillMount",value:function(){console.log("componentWillMount")}},{key:"componentDidMount",value:function(){console.log("componentDidMount")}},{key:"componentWillUpdate",value:function(){console.log("componentWillUpdate")}},{key:"render",value:function(){var t=this;return h.createElement("div",null,h.createElement("h1",null,"stbui demo",(new Date).toLocaleTimeString()),h.createElement("h1",null,"number: ",this.state.num),h.createElement("button",{style:{padding:"10px",backgroundColor:"#f00",color:"#fff"},onClick:function(){return c(this,t),this.onClick()}.bind(this)},"button"))}}]),e}());console.log(h.createElement(g,null)),v.render(h.createElement(g,null),document.getElementById("app"))}]);',
                                            nodeType: 3,
                                            id: 405,
                                        },
                                    ],
                                },
                                { textContent: '\n', nodeType: 3, id: 299 },
                            ],
                        },
                    ],
                },
            },
        },
        {
            index: 0,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2,
            timestamp: 1574605136264,
            type: 'url_change',
            data: { url: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 1,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 5,
            timestamp: 1574605136267,
            type: 'mouse_move',
            data: { x: 355, y: 206, pageX: 355, pageY: 206 },
        },
        {
            index: 2,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 16,
            timestamp: 1574605136278,
            type: 'mouse_out',
            data: { id: 377 },
        },
        {
            index: 3,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 16,
            timestamp: 1574605136278,
            type: 'mouse_over',
            data: { id: 2 },
        },
        {
            index: 4,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 1290,
            timestamp: 1574605137552,
            type: 'mouse_move',
            data: { x: 350, y: 227, pageX: 350, pageY: 227 },
        },
        {
            index: 5,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 1394,
            timestamp: 1574605137656,
            type: 'mouse_move',
            data: { x: 324, y: 310, pageX: 324, pageY: 310 },
        },
        {
            index: 6,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 1483,
            timestamp: 1574605137745,
            type: 'mouse_out',
            data: { id: 2 },
        },
        {
            index: 0,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2417,
            timestamp: 1574605138679,
            type: 'mouse_over',
            data: { id: 2 },
        },
        {
            index: 1,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2417,
            timestamp: 1574605138679,
            type: 'mouse_move',
            data: { x: 169, y: 424, pageX: 169, pageY: 424 },
        },
        {
            index: 3,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2506,
            timestamp: 1574605138768,
            type: 'mouse_over',
            data: { id: 377 },
        },
        {
            index: 2,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2506,
            timestamp: 1574605138768,
            type: 'mouse_out',
            data: { id: 2 },
        },
        {
            index: 4,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2523,
            timestamp: 1574605138785,
            type: 'mouse_move',
            data: { x: 67, y: 213, pageX: 67, pageY: 213 },
        },
        {
            index: 6,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2529,
            timestamp: 1574605138791,
            type: 'mouse_over',
            data: { id: 495 },
        },
        {
            index: 5,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2529,
            timestamp: 1574605138791,
            type: 'mouse_out',
            data: { id: 377 },
        },
        {
            index: 7,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 2867,
            timestamp: 1574605139129,
            type: 'mouse_move',
            data: { x: 62, y: 209, pageX: 62, pageY: 209 },
        },
        {
            index: 8,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3004,
            timestamp: 1574605139266,
            type: 'mouse_move',
            data: { x: 55, y: 204, pageX: 55, pageY: 204 },
        },
        {
            index: 9,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3102,
            timestamp: 1574605139364,
            type: 'mouse_click',
            data: {
                x: 54,
                y: 204,
                pageX: 54,
                pageY: 204,
                selector: [
                    { tagName: 'BUTTON', classes: [] },
                    { tagName: 'DIV', classes: [] },
                    { tagName: 'DIV', classes: [], id: 'app' },
                ],
            },
        },
        {
            index: 10,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3267,
            timestamp: 1574605139529,
            type: 'dom_mutation',
            data: {
                addedOrMoved: [
                    { parentId: 230, node: { tagName: 'DIV', nodeType: 1, id: 702 } },
                    { parentId: 702, node: { tagName: 'H1', nodeType: 1, id: 740 } },
                    { parentId: 740, node: { textContent: 'stbui demo', nodeType: 3, id: 779 } },
                    {
                        parentId: 740,
                        previousSiblingId: 779,
                        node: { textContent: '下午10:18:59', nodeType: 3, id: 819 },
                    },
                    { parentId: 702, previousSiblingId: 740, node: { tagName: 'H1', nodeType: 1, id: 860 } },
                    { parentId: 860, node: { textContent: 'number: ', nodeType: 3, id: 902 } },
                    { parentId: 860, previousSiblingId: 902, node: { textContent: '1', nodeType: 3, id: 945 } },
                    {
                        parentId: 702,
                        previousSiblingId: 860,
                        node: {
                            tagName: 'BUTTON',
                            attributes: [
                                {
                                    name: 'style',
                                    value:
                                        'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                },
                            ],
                            nodeType: 1,
                            id: 989,
                        },
                    },
                    { parentId: 989, node: { textContent: 'button', nodeType: 3, id: 1034 } },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 11,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3267,
            timestamp: 1574605139529,
            type: 'dom_mutation',
            data: {
                removed: [
                    { id: 377 },
                    { id: 434 },
                    { id: 527 },
                    { id: 560 },
                    { id: 464 },
                    { id: 594 },
                    { id: 629 },
                    { id: 495 },
                    { id: 665 },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 12,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3267,
            timestamp: 1574605139529,
            type: 'dom_mutation',
            data: { pageUrl: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 13,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3268,
            timestamp: 1574605139530,
            type: 'mouse_over',
            data: { id: 989 },
        },
        {
            index: 14,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3496,
            timestamp: 1574605139758,
            type: 'mouse_click',
            data: {
                x: 54,
                y: 204,
                pageX: 54,
                pageY: 204,
                selector: [
                    { tagName: 'BUTTON', classes: [] },
                    { tagName: 'DIV', classes: [] },
                    { tagName: 'DIV', classes: [], id: 'app' },
                ],
            },
        },
        {
            index: 18,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3620,
            timestamp: 1574605139882,
            type: 'mouse_over',
            data: { id: 1430 },
        },
        {
            index: 16,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3620,
            timestamp: 1574605139882,
            type: 'dom_mutation',
            data: {
                removed: [
                    { id: 702 },
                    { id: 740 },
                    { id: 779 },
                    { id: 819 },
                    { id: 860 },
                    { id: 902 },
                    { id: 945 },
                    { id: 989 },
                    { id: 1034 },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 15,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3620,
            timestamp: 1574605139882,
            type: 'dom_mutation',
            data: {
                addedOrMoved: [
                    { parentId: 230, node: { tagName: 'DIV', nodeType: 1, id: 1080 } },
                    { parentId: 1080, node: { tagName: 'H1', nodeType: 1, id: 1127 } },
                    { parentId: 1127, node: { textContent: 'stbui demo', nodeType: 3, id: 1175 } },
                    {
                        parentId: 1127,
                        previousSiblingId: 1175,
                        node: { textContent: '下午10:18:59', nodeType: 3, id: 1224 },
                    },
                    { parentId: 1080, previousSiblingId: 1127, node: { tagName: 'H1', nodeType: 1, id: 1274 } },
                    { parentId: 1274, node: { textContent: 'number: ', nodeType: 3, id: 1325 } },
                    { parentId: 1274, previousSiblingId: 1325, node: { textContent: '2', nodeType: 3, id: 1377 } },
                    {
                        parentId: 1080,
                        previousSiblingId: 1274,
                        node: {
                            tagName: 'BUTTON',
                            attributes: [
                                {
                                    name: 'style',
                                    value:
                                        'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                },
                            ],
                            nodeType: 1,
                            id: 1430,
                        },
                    },
                    { parentId: 1430, node: { textContent: 'button', nodeType: 3, id: 1484 } },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 17,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3620,
            timestamp: 1574605139882,
            type: 'dom_mutation',
            data: { pageUrl: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 19,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3785,
            timestamp: 1574605140047,
            type: 'mouse_click',
            data: {
                x: 54,
                y: 204,
                pageX: 54,
                pageY: 204,
                selector: [
                    { tagName: 'BUTTON', classes: [] },
                    { tagName: 'DIV', classes: [] },
                    { tagName: 'DIV', classes: [], id: 'app' },
                ],
            },
        },
        {
            index: 20,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3885,
            timestamp: 1574605140147,
            type: 'dom_mutation',
            data: {
                addedOrMoved: [
                    { parentId: 230, node: { tagName: 'DIV', nodeType: 1, id: 1539 } },
                    { parentId: 1539, node: { tagName: 'H1', nodeType: 1, id: 1595 } },
                    { parentId: 1595, node: { textContent: 'stbui demo', nodeType: 3, id: 1652 } },
                    {
                        parentId: 1595,
                        previousSiblingId: 1652,
                        node: { textContent: '下午10:19:00', nodeType: 3, id: 1710 },
                    },
                    { parentId: 1539, previousSiblingId: 1595, node: { tagName: 'H1', nodeType: 1, id: 1769 } },
                    { parentId: 1769, node: { textContent: 'number: ', nodeType: 3, id: 1829 } },
                    { parentId: 1769, previousSiblingId: 1829, node: { textContent: '3', nodeType: 3, id: 1890 } },
                    {
                        parentId: 1539,
                        previousSiblingId: 1769,
                        node: {
                            tagName: 'BUTTON',
                            attributes: [
                                {
                                    name: 'style',
                                    value:
                                        'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                },
                            ],
                            nodeType: 1,
                            id: 1952,
                        },
                    },
                    { parentId: 1952, node: { textContent: 'button', nodeType: 3, id: 2015 } },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 22,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3885,
            timestamp: 1574605140147,
            type: 'dom_mutation',
            data: { pageUrl: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 21,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3885,
            timestamp: 1574605140147,
            type: 'dom_mutation',
            data: {
                removed: [
                    { id: 1080 },
                    { id: 1127 },
                    { id: 1175 },
                    { id: 1224 },
                    { id: 1274 },
                    { id: 1325 },
                    { id: 1377 },
                    { id: 1430 },
                    { id: 1484 },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 23,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 3886,
            timestamp: 1574605140148,
            type: 'mouse_over',
            data: { id: 1952 },
        },
        {
            index: 24,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4052,
            timestamp: 1574605140314,
            type: 'mouse_click',
            data: {
                x: 54,
                y: 204,
                pageX: 54,
                pageY: 204,
                selector: [
                    { tagName: 'BUTTON', classes: [] },
                    { tagName: 'DIV', classes: [] },
                    { tagName: 'DIV', classes: [], id: 'app' },
                ],
            },
        },
        {
            index: 27,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4133,
            timestamp: 1574605140395,
            type: 'dom_mutation',
            data: { pageUrl: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 26,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4133,
            timestamp: 1574605140395,
            type: 'dom_mutation',
            data: {
                removed: [
                    { id: 1539 },
                    { id: 1595 },
                    { id: 1652 },
                    { id: 1710 },
                    { id: 1769 },
                    { id: 1829 },
                    { id: 1890 },
                    { id: 1952 },
                    { id: 2015 },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 25,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4133,
            timestamp: 1574605140395,
            type: 'dom_mutation',
            data: {
                addedOrMoved: [
                    { parentId: 230, node: { tagName: 'DIV', nodeType: 1, id: 2079 } },
                    { parentId: 2079, node: { tagName: 'H1', nodeType: 1, id: 2144 } },
                    { parentId: 2144, node: { textContent: 'stbui demo', nodeType: 3, id: 2210 } },
                    {
                        parentId: 2144,
                        previousSiblingId: 2210,
                        node: { textContent: '下午10:19:00', nodeType: 3, id: 2277 },
                    },
                    { parentId: 2079, previousSiblingId: 2144, node: { tagName: 'H1', nodeType: 1, id: 2345 } },
                    { parentId: 2345, node: { textContent: 'number: ', nodeType: 3, id: 2414 } },
                    { parentId: 2345, previousSiblingId: 2414, node: { textContent: '4', nodeType: 3, id: 2484 } },
                    {
                        parentId: 2079,
                        previousSiblingId: 2345,
                        node: {
                            tagName: 'BUTTON',
                            attributes: [
                                {
                                    name: 'style',
                                    value:
                                        'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                },
                            ],
                            nodeType: 1,
                            id: 2555,
                        },
                    },
                    { parentId: 2555, node: { textContent: 'button', nodeType: 3, id: 2627 } },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 28,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4134,
            timestamp: 1574605140396,
            type: 'mouse_over',
            data: { id: 2555 },
        },
        {
            index: 0,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4260,
            timestamp: 1574605140522,
            type: 'mouse_click',
            data: {
                x: 54,
                y: 204,
                pageX: 54,
                pageY: 204,
                selector: [
                    { tagName: 'BUTTON', classes: [] },
                    { tagName: 'DIV', classes: [] },
                    { tagName: 'DIV', classes: [], id: 'app' },
                ],
            },
        },
        {
            index: 2,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4367,
            timestamp: 1574605140629,
            type: 'dom_mutation',
            data: {
                removed: [
                    { id: 2079 },
                    { id: 2144 },
                    { id: 2210 },
                    { id: 2277 },
                    { id: 2345 },
                    { id: 2414 },
                    { id: 2484 },
                    { id: 2555 },
                    { id: 2627 },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 1,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4367,
            timestamp: 1574605140629,
            type: 'dom_mutation',
            data: {
                addedOrMoved: [
                    { parentId: 230, node: { tagName: 'DIV', nodeType: 1, id: 2700 } },
                    { parentId: 2700, node: { tagName: 'H1', nodeType: 1, id: 2774 } },
                    { parentId: 2774, node: { textContent: 'stbui demo', nodeType: 3, id: 2849 } },
                    {
                        parentId: 2774,
                        previousSiblingId: 2849,
                        node: { textContent: '下午10:19:00', nodeType: 3, id: 2925 },
                    },
                    { parentId: 2700, previousSiblingId: 2774, node: { tagName: 'H1', nodeType: 1, id: 3002 } },
                    { parentId: 3002, node: { textContent: 'number: ', nodeType: 3, id: 3080 } },
                    { parentId: 3002, previousSiblingId: 3080, node: { textContent: '5', nodeType: 3, id: 3159 } },
                    {
                        parentId: 2700,
                        previousSiblingId: 3002,
                        node: {
                            tagName: 'BUTTON',
                            attributes: [
                                {
                                    name: 'style',
                                    value:
                                        'padding: 10px; background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);',
                                },
                            ],
                            nodeType: 1,
                            id: 3239,
                        },
                    },
                    { parentId: 3239, node: { textContent: 'button', nodeType: 3, id: 3320 } },
                ],
                pageUrl: 'http://127.0.0.1:8081/test.html',
            },
        },
        {
            index: 4,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4367,
            timestamp: 1574605140629,
            type: 'mouse_over',
            data: { id: 3239 },
        },
        {
            index: 3,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4367,
            timestamp: 1574605140629,
            type: 'dom_mutation',
            data: { pageUrl: 'http://127.0.0.1:8081/test.html' },
        },
        {
            index: 5,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4428,
            timestamp: 1574605140690,
            type: 'mouse_move',
            data: { x: 54, y: 204, pageX: 54, pageY: 204 },
        },
        {
            index: 7,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4460,
            timestamp: 1574605140722,
            type: 'mouse_over',
            data: { id: 2 },
        },
        {
            index: 6,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4460,
            timestamp: 1574605140722,
            type: 'mouse_out',
            data: { id: 3239 },
        },
        {
            index: 8,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4532,
            timestamp: 1574605140794,
            type: 'mouse_move',
            data: { x: 116, y: 309, pageX: 116, pageY: 309 },
        },
        {
            index: 9,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 4621,
            timestamp: 1574605140883,
            type: 'mouse_out',
            data: { id: 2 },
        },
        {
            index: 0,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8585,
            timestamp: 1574605144847,
            type: 'mouse_over',
            data: { id: 2 },
        },
        {
            index: 1,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8585,
            timestamp: 1574605144847,
            type: 'mouse_move',
            data: { x: 298, y: 423, pageX: 298, pageY: 423 },
        },
        {
            index: 2,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8886,
            timestamp: 1574605145148,
            type: 'mouse_move',
            data: { x: 246, y: 222, pageX: 246, pageY: 222 },
        },
        {
            index: 4,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8894,
            timestamp: 1574605145156,
            type: 'mouse_over',
            data: { id: 2700 },
        },
        {
            index: 3,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8894,
            timestamp: 1574605145156,
            type: 'mouse_out',
            data: { id: 2 },
        },
        {
            index: 6,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8950,
            timestamp: 1574605145212,
            type: 'mouse_over',
            data: { id: 3002 },
        },
        {
            index: 5,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8950,
            timestamp: 1574605145212,
            type: 'mouse_out',
            data: { id: 2700 },
        },
        {
            index: 8,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8974,
            timestamp: 1574605145236,
            type: 'mouse_over',
            data: { id: 2700 },
        },
        {
            index: 7,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8974,
            timestamp: 1574605145236,
            type: 'mouse_out',
            data: { id: 3002 },
        },
        {
            index: 10,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8982,
            timestamp: 1574605145244,
            type: 'mouse_over',
            data: { id: 2774 },
        },
        {
            index: 9,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8982,
            timestamp: 1574605145244,
            type: 'mouse_out',
            data: { id: 2700 },
        },
        {
            index: 11,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8990,
            timestamp: 1574605145252,
            type: 'mouse_move',
            data: { x: 111, y: 60, pageX: 111, pageY: 60 },
        },
        {
            index: 12,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8998,
            timestamp: 1574605145260,
            type: 'mouse_out',
            data: { id: 2774 },
        },
        {
            index: 13,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 8998,
            timestamp: 1574605145260,
            type: 'mouse_over',
            data: { id: 14 },
        },
        {
            index: 15,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9014,
            timestamp: 1574605145276,
            type: 'mouse_over',
            data: { id: 189 },
        },
        {
            index: 14,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9014,
            timestamp: 1574605145276,
            type: 'mouse_out',
            data: { id: 14 },
        },
        {
            index: 17,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9038,
            timestamp: 1574605145300,
            type: 'mouse_over',
            data: { id: 14 },
        },
        {
            index: 16,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9038,
            timestamp: 1574605145300,
            type: 'mouse_out',
            data: { id: 189 },
        },
        {
            index: 18,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9047,
            timestamp: 1574605145309,
            type: 'mouse_out',
            data: { id: 14 },
        },
        {
            index: 19,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9047,
            timestamp: 1574605145309,
            type: 'mouse_over',
            data: { id: 2 },
        },
        {
            index: 20,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9312,
            timestamp: 1574605145574,
            type: 'mouse_move',
            data: { x: 73, y: 3, pageX: 73, pageY: 3 },
        },
        {
            index: 21,
            serverSessionId: '5dda91504aea244982de72d1',
            time: 9329,
            timestamp: 1574605145591,
            type: 'mouse_out',
            data: { id: 2 },
        },
    ],
    lastEventIndex: 1,
    lastEventTimestamp: 1574605145591,
    offset: 0,
};
