import * as mongoose from 'mongoose';

export const SnapshotSchema = new mongoose.Schema({
  browserName: String,
  browserVersion: String,
  // city: String,
  clientStartMilliseconds: Number,
  // country: String,
  docType: String,
  // hasInaccessibleResources: String,
  // id: String,
  // ip: String,
  // isLive: Boolean,
  // isWatched: Boolean,
  lastActive: Number,
  layoutName: String,
  left: Number,
  // length: Number,
  manufacturer: String,
  origin: String,
  os: String,
  pageUrl: String,
  product: String,
  referrer: String,
  screenHeight: Number,
  screenWidth: Number,
  sensitiveInputFields: Boolean,
  snapshot: Object,
  timestamp: Number,
  start: Number,
  top: Number,
  // userIdentity: Object,
  version: String,
  visibilityState: String,
});
